name: Build 

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: LawPanel.ApiClient.sln

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.0
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Restore NuGet pckages
      run: nuget restore ${{ env.AZURE_WEBAPP_NAME }}

    - name: Build
      run: msbuild ${{ env.AZURE_WEBAPP_NAME }} /p:Configuration=Release
